### ISSUE TITLE
Is Linux 64 bit v1.0.4 testing possible?

### ISSUE THREAD

**Issue by danballance** [pierreguillot/Camomile#105]
Firstly can I thank you for this awesome project. I am a web developer by profession and a musician in my spare time. I'm currently learning PD and I'm trying to create some plugins that manipulate midi within my DAW. This project is amazing and I will do my best to support it, although I am not a C or audio programmer unfortunately. (Yet!)
 
I noticed in some other tickets that there are some links to Windows 64 bit binaries for v1.0.4 to test with. Is it possible for me to do some testing on Linux 64 bit against this new version? Apologies if I have missed something obvious.

**Comment by pierreguillot** [comment]
Hi, thanks! Yes, the Windows continuous integration (Appveyor CI) uploads automatically each new build but the Linux & Mac continuous integration (Travis CI) doesn't provide such feature. The only way to get it is to compile (otherwise I should upload the binary each time I compile on a system). The instructions are on the [wiki](https://github.com/pierreguillot/Camomile/wiki) and in the file [.travis.yml](https://github.com/pierreguillot/Camomile/blob/master/.travis.yml). Anyway, the v1.0.4 should be ready pretty soon.

**Comment by pierreguillot** [comment]
You can download it now ;)
