### ISSUE TITLE
Loading a wav file causes Camomile to crash.

### ISSUE THREAD

**Issue by ilambert** [pierreguillot/Camomile#137]
OS: Ubuntu Linux 18.04
DAW: Renoise 3.1.1
Plugin: VST2 v1.0.6
Audio: 44100 Hz

When I try to load a wav file in the attached patch, It crashes. 
Running my DAW from the terminal, it outputs: "Operation not permitted"

Not sure if I'm doing something wrong, but if so; anyone is welcome to tell me what to do instead. 
[granularSampler.zip](https://github.com/pierreguillot/Camomile/files/2394478/granularSampler.zip)

**Comment by pierreguillot** [comment]
I think the problem comes from the result of [r openpanel] that is not well formatted. After [r openpanel] before sending directly the symbol result to the trigger
```
[r openpanel]
|
[t b a]
|
```
can you add a [symbol] to "force" the formatting
```
[r openpanel]
|
[symbol]
|
[t b a]
|
```

If it works, I'll try to correct the bug directly in the plugin to avoid such workaround.

PS: Instead of using `[set symbol $1(` on a `[message(` to save the audio file name, you should use to data save-load mechanism of the [program](https://github.com/pierreguillot/Camomile/wiki/How-to-create-new-plugins#programs).

**Comment by ilambert** [comment]
That worked! Thank you very much. I'll try out your other suggestion as well. This is admittedly just a copy/paste port of one of Martin Brinkmann's granulators which I've always enjoyed using in my patches. 
:smile: 

Thanks again. More people need to see the power of this plugin.
