### ISSUE TITLE
Openpanel does not play the file

### ISSUE THREAD

**Issue by Schorschua-Phrosch** [pierreguillot/Camomile#141]
Environment:
Windows 10, 64 bit
Pure Data 0.49-0
Camomile 1.0.7
Reaper 5.96 64 bit

          

The vst I created via Camomile from my PD Patch lets me choose an Audio file (I chose .wav files) but doesnt play them. Choosing a file with only white noise on it, I get data in the DAW but no sound. Looking steady like this.

<img width="239" alt="mixer" src="https://user-images.githubusercontent.com/44024742/46733808-9b24bb00-cc91-11e8-97ac-09129320ae9c.png">

I attach the folder, which I loaded in my VST folder.
[openpanel.zip](https://github.com/pierreguillot/Camomile/files/2464482/openpanel.zip)

**Comment by pierreguillot** [comment]
I tried your patch on my Mac with Reaper64 and it works well. I will test on a Windows machine ASAP to check if there is a difference. Do you have any message or warning in the console? And perhaps the problem is the sample rate initialization. You should try to retrieve the sample rate when the DSP status changed (see this issue: https://github.com/pierreguillot/Camomile/issues/83).

**Comment by Schorschua-Phrosch** [comment]
I have found the problem. the expression object didnt work in Reaper. In the console I saw that it gives a Syntax error. I tried it out with a patch only containing [ expr ] math. The same thing. I guess there is the bug.

**Comment by pierreguillot** [comment]
So this can be related to this issue: https://github.com/pierreguillot/Camomile/issues/139. In your patch if you use a simple object `[/  ]` instead (because you use `[expr]` only for a division), does it work?

**Comment by Schorschua-Phrosch** [comment]
It does work with the simple division object. Thank you very much!
