### ISSUE TITLE
./camomile mv .so in the respective folder

### ISSUE THREAD

**Issue by patricksebastien** [pierreguillot/Camomile#162]
Using the linux version of the script ./camomile, it works. I have 2 requests:

1. Have an option to specify what format (lv2, vst) to output (Nice to have)
2. The resulting .so should be move in the folder containing the .pd files etc. In the example, AlmondOrgan.so is located in the Plugins/builds, not in Plugins/builds/AlmondOrgan/

Am I right saying that it will not work if the .so is not inside the plugin folder (.pd, .txt, .png...)?

**Comment by muziker** [comment]
Hey does the lv2 almondorgan work in a DAW?

**Comment by patricksebastien** [comment]
[Was not able to build the LV2](https://github.com/pierreguillot/Camomile/issues/158) and also Bitwig is not compatible with LV2.

**Comment by pierreguillot** [comment]
1. If you delete the binary corresponding to a format, this plugin will not be generated. You will only get a warning telling you that the format was not found. But if you would like an option to specify the format, can you create a specific issue?

2. Can you open the camomile script with a text editor and replace the line 456:
`cp -f "$ThisPath/$camo_name.$LinuxVstExtension" $plugin_output_dir/$plugin_name.$LinuxVstExtension`
by
`cp -f "$ThisPath/$camo_name.$LinuxVstExtension" $plugin_output_dir/$plugin_name/$plugin_name.$LinuxVstExtension` ?
If it works I will fix this for 0.0.7

**Comment by theotherjenkutler** [comment]
I tried this change on OSX 10.11.6, so I changed line 370 instead to         
`cp -rf $ThisPath/$camo_name.$AppleVstExtension $plugin_output_dir/$plugin_name/$plugin_name.$AppleVstExtension `

Here are the errors:

`Camomile - Plugin Generator
cp: ./builds/Bulgroz/Bulgroz.vst: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst: unable to copy extended attributes to ./builds/Bulgroz/Bulgroz.vst: No such file or directory
cp: ./builds/Bulgroz/Bulgroz.vst/Contents: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents: unable to copy extended attributes to ./builds/Bulgroz/Bulgroz.vst/Contents: No such file or directory
cp: ./builds/Bulgroz/Bulgroz.vst/Contents/Info.plist: No such file or directory
cp: ./builds/Bulgroz/Bulgroz.vst/Contents/MacOS: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents/MacOS: unable to copy extended attributes to ./builds/Bulgroz/Bulgroz.vst/Contents/MacOS: No such file or directory
cp: ./builds/Bulgroz/Bulgroz.vst/Contents/MacOS/CamomileFx: No such file or directory
cp: ./builds/Bulgroz/Bulgroz.vst/Contents/PkgInfo: No such file or directory
cp: ./builds/Bulgroz/Bulgroz.vst/Contents/Resources: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents/Resources: unable to copy extended attributes to ./builds/Bulgroz/Bulgroz.vst/Contents/Resources: No such file or directory
cp: ./builds/Bulgroz/Bulgroz.vst/Contents/Resources/RecentFilesMenuTemplate.nib: No such file or directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
./builds/Bulgroz.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/Bulgroz.vst/Contents/Info.plist, NSUnderlyingError=0x7fdcc0c0e830 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/Bulgroz.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/Bulgroz.vst/Contents/Info.plist, NSUnderlyingError=0x7fbc4040e830 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/Bulgroz.vst
./builds/Bulgroz.vst3
./builds/Bulgroz.component
./builds/Bulgroz.lv2
cp: ./builds/Castafiore/Castafiore.vst: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst: unable to copy extended attributes to ./builds/Castafiore/Castafiore.vst: No such file or directory
cp: ./builds/Castafiore/Castafiore.vst/Contents: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents: unable to copy extended attributes to ./builds/Castafiore/Castafiore.vst/Contents: No such file or directory
cp: ./builds/Castafiore/Castafiore.vst/Contents/Info.plist: No such file or directory
cp: ./builds/Castafiore/Castafiore.vst/Contents/MacOS: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents/MacOS: unable to copy extended attributes to ./builds/Castafiore/Castafiore.vst/Contents/MacOS: No such file or directory
cp: ./builds/Castafiore/Castafiore.vst/Contents/MacOS/CamomileFx: No such file or directory
cp: ./builds/Castafiore/Castafiore.vst/Contents/PkgInfo: No such file or directory
cp: ./builds/Castafiore/Castafiore.vst/Contents/Resources: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents/Resources: unable to copy extended attributes to ./builds/Castafiore/Castafiore.vst/Contents/Resources: No such file or directory
cp: ./builds/Castafiore/Castafiore.vst/Contents/Resources/RecentFilesMenuTemplate.nib: No such file or directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
./builds/Castafiore.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/Castafiore.vst/Contents/Info.plist, NSUnderlyingError=0x7fd38bc0e840 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/Castafiore.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/Castafiore.vst/Contents/Info.plist, NSUnderlyingError=0x7fefc140e840 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/Castafiore.vst
./builds/Castafiore.vst3
./builds/Castafiore.component
./builds/Castafiore.lv2
cp: ./builds/MiniMock/MiniMock.vst: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/Camomile.vst: unable to copy extended attributes to ./builds/MiniMock/MiniMock.vst: No such file or directory
cp: ./builds/MiniMock/MiniMock.vst/Contents: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/Camomile.vst/Contents: unable to copy extended attributes to ./builds/MiniMock/MiniMock.vst/Contents: No such file or directory
cp: ./builds/MiniMock/MiniMock.vst/Contents/Info.plist: No such file or directory
cp: ./builds/MiniMock/MiniMock.vst/Contents/MacOS: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/Camomile.vst/Contents/MacOS: unable to copy extended attributes to ./builds/MiniMock/MiniMock.vst/Contents/MacOS: No such file or directory
cp: ./builds/MiniMock/MiniMock.vst/Contents/MacOS/Camomile: No such file or directory
cp: ./builds/MiniMock/MiniMock.vst/Contents/PkgInfo: No such file or directory
cp: ./builds/MiniMock/MiniMock.vst/Contents/Resources: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/Camomile.vst/Contents/Resources: unable to copy extended attributes to ./builds/MiniMock/MiniMock.vst/Contents/Resources: No such file or directory
cp: ./builds/MiniMock/MiniMock.vst/Contents/Resources/RecentFilesMenuTemplate.nib: No such file or directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
./builds/MiniMock.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/MiniMock.vst/Contents/Info.plist, NSUnderlyingError=0x7fd162c0e830 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/MiniMock.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/MiniMock.vst/Contents/Info.plist, NSUnderlyingError=0x7fde3ac0e830 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/MiniMock.vst
./builds/MiniMock.vst3
./builds/MiniMock.component
./builds/MiniMock.lv2
cp: ./builds/PdStalFx/PdStalFx.vst: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst: unable to copy extended attributes to ./builds/PdStalFx/PdStalFx.vst: No such file or directory
cp: ./builds/PdStalFx/PdStalFx.vst/Contents: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents: unable to copy extended attributes to ./builds/PdStalFx/PdStalFx.vst/Contents: No such file or directory
cp: ./builds/PdStalFx/PdStalFx.vst/Contents/Info.plist: No such file or directory
cp: ./builds/PdStalFx/PdStalFx.vst/Contents/MacOS: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents/MacOS: unable to copy extended attributes to ./builds/PdStalFx/PdStalFx.vst/Contents/MacOS: No such file or directory
cp: ./builds/PdStalFx/PdStalFx.vst/Contents/MacOS/CamomileFx: No such file or directory
cp: ./builds/PdStalFx/PdStalFx.vst/Contents/PkgInfo: No such file or directory
cp: ./builds/PdStalFx/PdStalFx.vst/Contents/Resources: No such file or directory
cp: /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/CamomileFx.vst/Contents/Resources: unable to copy extended attributes to ./builds/PdStalFx/PdStalFx.vst/Contents/Resources: No such file or directory
cp: ./builds/PdStalFx/PdStalFx.vst/Contents/Resources/RecentFilesMenuTemplate.nib: No such file or directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
./builds/PdStalFx.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/PdStalFx.vst/Contents/Info.plist, NSUnderlyingError=0x7f8e08600b50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/PdStalFx.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/PdStalFx.vst/Contents/Info.plist, NSUnderlyingError=0x7fe68a502db0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/PdStalFx.vst
./builds/PdStalFx.vst3
./builds/PdStalFx.component
./builds/PdStalFx.lv2
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
./builds/earth.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/earth.vst/Contents/Info.plist, NSUnderlyingError=0x7f9980c0e830 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/earth.vst/Contents/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=./builds/earth.vst/Contents/Info.plist, NSUnderlyingError=0x7fbd6040e830 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
./builds/earth.vst
./builds/earth.vst3
./builds/earth.component
./camomile: line 177:   990 Segmentation fault: 11  $ThisPath/lv2_file_generator $plugin_output_dir/$plugin_name.lv2/$plugin_name.$AppleLV2Extension $plugin_name > /dev/null
mv: rename /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/manifest.ttl to ./builds/earth.lv2/manifest.ttl: No such file or directory
mv: rename /Users/JenKutler/Desktop/atmosphericConditions/_BACKUP/Camomile/Plugins/earth.ttl to ./builds/earth.lv2/earth.ttl: No such file or directory
`
I hope that helps.

**Comment by pierreguillot** [comment]
There are many subjects related to different OS in this issue, if you still encounter any problem please create a new issue more specific to a problem or a request. For the moment, I close this one.
