### ISSUE TITLE
Examples no longer work in v1.0.7-beta13

### ISSUE THREAD

**Issue by fotisandstuff** [pierreguillot/Camomile#190]
AlmondOrgan, MiniMock etc. no longer produce any sound in v1.0.7-beta13. I'm using Reaper v6.13 on Win 10 x64.

**Comment by pierreguillot** [comment]
Could you be more specific? Which plugins exactly? All the examples? Did you have any sound on your track? Did you give MIDI notes to the MIDI plugins? What are the parameters? What do you mean by "no longer"? etc.

**Comment by alfonso73** [comment]
Hi, it works for me on Reaper 6.13 - Win10 x64
At first they didn't sound because all the relevant volume controls in the
patches where turned down...i don't remember if it was the same thing with
examples of previous Camomile versions

a.


www.elgallorojorecords.bandcamp.com/
<https://elgallorojorecords.bandcamp.com/>
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by pierreguillot** [comment]
Ok, it should be fixed here https://github.com/pierreguillot/Camomile/releases/tag/v1.0.7-beta14.
