### ISSUE TITLE
Parameter controls in visible area do not work when patched

### ISSUE THREAD

**Issue by wagwog** [pierreguillot/Camomile#22]
It seems that Pd and Camomile are broken in an opposite way when it comes to gui controls.

Controls within the visible area which use direct connections do work in Pd, but do not work in Camomile.

Controls within the visible area that use a receive object do not work within Pd, but these controls do work in Camomile.

And in Pd, any controls outside of the visible area seem to work fine, whether directly connected or using a receive object.

I am using Pd 0.46.7 and Camomille 0.0.7.

**Comment by pierreguillot** [comment]
I don't really understand what is control. Do you mean parameters ? There is a simple but specific way to define parameters in Camomile. The plugin send messages via the receive symbols of GUIs, this is the only way to do it (everything is explained in the wiki and the FAQ). If you want to have a patch that works in PD and Camomile with  wireless connections, there is a small trick. You must also set a send symbol to the GUIs (for example $0-rate for the receive symbol and $0-rate-s for the send symbol) and use the send symbol in your patch. This way for example, when you move a slider  in PD, it sends the value to the patch via its send symbol. And when the plugin sends the value via the receive symbol of the slider, the slider sends back the value to the patch via its send symbol. You can have a look to the patches camo.minimock~ or camo.almond~. I hope I answered your question. If not, can you send me patch as example and tell what is your OS and your DAW.

**Comment by wagwog** [comment]
My os is Windows 7, and my daw is Reaper.

I was partially wrong in what I said in my last post.  Pd seems to be behaving as it should.  But Camomile seems to have a problem with sends and receives.  I think maybe there is a language barrier problem here about sends and receives.  Here are some patches to demonstrate the behavior, and I created another patch to demonstrate send and receive behavior in an effort to make the problem as clear and obvious as I could:  https://app.box.com/s/h2dzx4vgvuppnhic5yb3kmqh258vf76n

Thanks.

Also, thanks for making Camomile!  I have wanted to use Pd patches as vst plugins for a long time.

**Comment by pierreguillot** [comment]
I think you misunderstood the behavior of the plugin. I resume the behavior of your patches to ensure that we don't have a really strange difference between our two versions:

* send-receive-behavior-examples.pd:
 * 1. The slider controls the numbox with a link.
 * 2. The slider controls the numbox with its send symbol because the numbox uses this send symbol as a receive symbol.
 * 3. The numbox controls the slider with its send symbol because the slider uses this send symbol as a receive symbol.
 * 4. None of them controls the other because they only use the same receive symbol.
 * 5. None of them controls the other because they only use the same send symbol.
 * 6. The slider controls the numbox with a link and the numbox controls the slider with its send symbol because the slider uses this send symbol as a receive symbol so there is a stack overflow.

* test-patch-direct-connection.pd:
`This patch works in Pd. It does not work in Camomile.`
Because the slider doesn't have any receive symbol, in the section "How to create patches" of the wiki, this is explained.To create a plugin parameter you must create a GUI with a label and a receive symbol to communicate with the patch.

* test-patch-send-receive-connection.pd
`This patch works inside Pd. It does not work in Camomile.`
Same problem, you didn't set a receive symbol.

* test-patch-receive-receive-connection.pd
`This patch does not work in Pd, but it does work in Camomile.` 
In fact, it works in PD but not like you want. As explained above, the solution is to set a send symbol to the slider and to use this one in the patch. To understand how the plugin works, you can imagine a second slider with a send symbol that is the same as the receive symbol of the slider of the interface.

Here the solution:
[test-patch-connection.pd.zip](https://github.com/pierreguillot/Camomile/files/209748/test-patch-connection.pd.zip)

**Comment by wagwog** [comment]
> To understand how the plugin works, you can imagine a second slider with a send symbol that is the same as the receive symbol of the slider of the interface.

Ahhh.  I think this is mostly what tripped me up.  I didn't understand that Camomile sends  to the gui objects.  And even now that I know, it is still a little confusing to think about.  So, I should think of it as sends/receives between the plugin parameters (Camomile plugin) and the gui objects in the Pd patch, in addition to sends/receives between the gui objects and receiving objects in the Pd patch.  I was only thinking of interactions between gui objects (what I call controls)  and the receiving objects in the Pd patch.  And then I came to the wrong conclusion that there are problem was in Camomile.

And I must have passed over the parts in the wiki which say that a gui object must have a receive symbol and a label.

All apologies for the confusion.  And thanks so much for the explanation.

**Comment by pierreguillot** [comment]
In fact, Camomile uses the GUI to recognize which parameters/control you want to use and it uses the receive symbol of the GUI to send the messages. So if you use this symbol somewhere else in your patch, the object will also receive the value. So yes, I think that the second slider is the right metaphor. I will add something about it in the documentation to avoid confusion.
Cheers
