### ISSUE TITLE
request: update to the latest libpd

### ISSUE THREAD

**Issue by porres** [pierreguillot/Camomile#220]
Hi, new libpd just came out and supports pd-0.51-4 (https://github.com/libpd/libpd/releases/tag/0.12.0)

are there any plans to update camomile with this update sometime soon?

thanks

**Comment by pierreguillot** [comment]
Hi, Pd and libpd are updated frequently on the dev branches and Pd is always up-to-date when a new release is published.

**Comment by pierreguillot** [comment]
Does it answer your question? May we close the issue?

**Comment by porres** [comment]
honestly I didn't get it, are you just saying that whenever you have a new release you'll have it with the latest version? Any idea on when that'd happen? but yeah, go ahead and close it ;)

**Comment by pierreguillot** [comment]
> are you just saying that whenever you have a new release you'll have it with the latest version?

Yes, the new releases use the latest Pd version (the main branch with sometimes some fixes for multi-instance/thread support) and if you look at the dev branches of Camomile, you'll see that Pd is frequently updated. As Pd is frequently updated, this request doesn't seem relevant (otherwise, each time a commit is pushed on the main branch of Pd, you'll have to submit again and again the same issue). But if you encounter a specific issue to resolve or you want to implement a specific feature that requires an update of Pd and that updating Pd leads to problems, feel free to create an issue. 

> Any idea on when that'd happen?

No

**Comment by porres** [comment]
it's just that else relies on features from the latest versions but I guess we (me and @emviveros) can try and compile it with the new Pd
