### ISSUE TITLE
No fine-control mode for sliders in VST3 plugin interface when Shift+dragging with mouse to change values

### ISSUE THREAD

**Issue by svavilov** [pierreguillot/Camomile#222]
Shift + drag on a slider in a Camomile plugin's interface does not switch it to high-accuracy fine adjustment mode, as it does in Pure Data (version 0-51-1).

This can be reproduced with the Bulgroz plugin, for example.

MacOS 10.15.7
Cockos Reaper 6.19
VST3 Plugin version

**Comment by pierreguillot** [comment]
This is fixed on dev/v1.0.8 and there is a [beta version](https://github.com/pierreguillot/Camomile/releases).

**Comment by jyg** [comment]
Hi, there are still some differences between pd 0.51.4 and camomile v1.0,8. (linux 64 vst3 Camomile plugin)
For a h-slider (range 0-127, width 128), high-accuracy fine adjustment step is 0.1 in camomile instead of 0.01 in pd-vanilla. 
Moreover, with normal mouse mode, mouse moves produce increments of 1 unit in pd-vanilla and of 0.97 in camomile. This can be problematic when the slider defines pitch with one unit = one semi-tone, as in midi note configuration (0-127), for example, in Automatonism patches.

Linux Lubuntu 18.04.5
Cockos Reaper 6.26
VST3 Plugin version

EDIT : in order to have integer steps with h-sliders in Camomile, I had to adjust the h-slider width to 125 (instead of 128 in pd-vanilla)

**Comment by pierreguillot** [comment]
Just to be sure, I fix it right:

> For a h-slider (range 0-127, width 128), high-accuracy fine adjustment step is 0.1 in camomile instead of 0.01 in pd-vanilla.

This doesn't depend on the width, or the range and this is also valid for vslider, isn't it?

> Moreover, with normal mouse mode, mouse moves produce increments of 1 unit in pd-vanilla and of 0.97 in camomile. 
> EDIT : in order to have integer steps with h-sliders in Camomile, I had to adjust the h-slider width to 125 (instead of 128 in pd-vanilla)

I think the increment is based on the value range and slider size. So I should remove 3 to the size of the slider when used to compute the value, is that it?

**Comment by jyg** [comment]
> > For a h-slider (range 0-127, width 128), high-accuracy fine adjustment step is 0.1 in camomile instead of 0.01 in pd-vanilla.
> 
> This doesn't depend on the width, or the range and this is also valid for vslider, isn't it?

Yes , it depends of the width (`x_gui.x_w`) and the range for vsl (same for vsl of course). For example :

- hsl with width = 64 and range 0..126 produces  increments 2 per pixel and 0.02 in fine-control mode
- hsl with width = 255 and range 0..127 increments 0.5 per pixel and 0.005 in fine-control mode

> > Moreover, with normal mouse mode, mouse moves produce increments of 1 unit in pd-vanilla and of 0.97 in camomile.
> > EDIT : in order to have integer steps with h-sliders in Camomile, I had to adjust the h-slider width to 125 (instead of 128 in pd-vanilla)
> 
> I think the increment is based on the value range and slider size. So I should remove 3 to the size of the slider when used to compute the value, is that it?

I think so, but I cannot understand why.  (the width of the drawn black rectangle for hslider is `x_gui.x_w`  + 5)

**Comment by pierreguillot** [comment]
I looked at Pd code and there are left and right offsets that (I guess) give a total of 7 pixels so I used width - 7 and it seems to fix the issue. For the fine control mode, I was using 0.1 instead of 0.01, I also fixed it. The CI is running and in a few minutes, you should be able to download binaries (https://github.com/pierreguillot/Camomile/actions/runs/797107915) can you test and tell me if it works? Thank you!

**Comment by jyg** [comment]
Hello, I just tried the Camomile-Linux64 artifact, but unfortunately Reaper cannot open it. I'll try on Windows asap.

**Comment by pierreguillot** [comment]
Do you have any error messages? I tried on Ubuntu 20.04 with Reaper 6.20 and it works.

**Comment by jyg** [comment]
Maybe the fact that I'm on Ubuntu 18.04.5   ?
The error message delivered by Reaper is "the following plugin effect couldn't be loaded"
I have to further investigate.

**Comment by pierreguillot** [comment]
I'll try to add a Ubuntu 18.04 VM so.

**Comment by pierreguillot** [comment]
Can you try this one https://github.com/pierreguillot/Camomile/actions/runs/809307975? Thank you!

**Comment by jyg** [comment]
> Can you try this one https://github.com/pierreguillot/Camomile/actions/runs/809307975? Thank you!

Yes It works.  And the range and increments for sliders work perfectly.
Many Thanks !
PS Does this mean that we may have to distribute 2 plugin versions, according to linux OS version ?

**Comment by pierreguillot** [comment]
>  PS Does this mean that we may have to distribute 2 plugin versions, according to linux OS version ?
Yes, because Ubuntu 20 and 18 are not compatible...

**Comment by jyg** [comment]
> Yes, because Ubuntu 20 and 18 are not compatible..

Strange, because so far I could use previous builds on ubuntu 18.04.5

**Comment by pierreguillot** [comment]
Because it was compiled on Travis with Ubuntu 16.04. I guess the binaries were not working on Ubuntu 20.04.
