### ISSUE TITLE
:((( ubuntu version crash when i try open patch 

### ISSUE THREAD

**Issue by artofmus** [pierreguillot/Camomile#37]
I trying use camomile on different version of linux and different software and always plugin normal load but  crashing when i try open patch, help me please? may be i did something wrong? for example bitwig try save plugin state, may be problem in permissions?

**Comment by pierreguillot** [comment]
Do you have any bug report ? Perhaps the problem is this one #21 ? Tell me more... 
Normally there is a dialog window when you open a patch. But on Linux it seems that depending on the GUI library, the plugin freezes. The problem comes from Juce and can be solved if you recompile with another GUI option.

**Comment by artofmus** [comment]
@pierreguillot yes this is very similar. 
I must recompile with juce error correction to fix it?

**Comment by pierreguillot** [comment]
Yes, you can try to add this preprocessor definition: `JUCE_DISABLE_NATIVE_FILECHOOSERS=1` and [recompile](https://github.com/pierreguillot/Camomile/wiki/Compilation).

**Comment by artofmus** [comment]
ok Thank you!

**Comment by pierreguillot** [comment]
I'll keep the #21 open, feel free to reopen this issue if the problem differs.
