### ISSUE TITLE
Camomile as Midi Effect

### ISSUE THREAD

**Issue by mcedmo** [pierreguillot/Camomile#42]
Thank you so much for taking the time to create this, I have been hoping someone would do it for years! 
I have not been able to get Ableton or Logic to recognize camomile as a midi effect so that I can use it as a sequencer. It has been working perfectly as an audio effect. I suspect I am missing something very simple. Does anyone know of a way to get this working?

**Comment by pierreguillot** [comment]
Is it a problem with MIDI in general or with just a specific use ? On Reaper, I can use MIDI (but I have a problem with note off #27). Perhaps it's a problem of effect vs synthesizer (#25, #40, #41). Otherwise can you give me further information ? What do you mean by "recognize camomile as a midi effect " ? What is your operating system (Linux, Windows, Mac, version, etc.) ?  What version of Camomile ?
Cheers
