### ISSUE TITLE
fft ? block~?

### ISSUE THREAD

**Issue by jdreske** [pierreguillot/Camomile#47]
Hi,
I tried to use a pd patch with fft. ( http://www.pd-tutorial.com/english/ch03s08.html )
It works good in pd vanilla and there is no error or warning in the camomile console.
no external abstractions involved.
The  patch does not produce any sound as a vst-plugin ( a simple osc~ added to the patch works however)
Is FFT and block~ expected to work inside Camomile? 
I cannot find a reason why the pd patch does not work inside Camomile.
I'm using Ableton live 9
Here is the .pd patch: https://drive.google.com/open?id=0ByVfkxBnSX-ATkJWc09fdHVHdDQ
(Just check the test - toggle to play a sound.)

**Comment by pierreguillot** [comment]
Hi,
I don't have any problem with [fft~] and [block~]. I think the problem is because you receive messages from the GUIs (the parameters) at each DSP tick and it resets the buffer 1003-gain3. You need to filter the changes with the [change] object (see the [FAQ](https://github.com/pierreguillot/Camomile/wiki/Frequently-Asked-Questions), **I receive messages even if the value of a parameter has not changed, why** ?). Also I suggest you to use $0 in the name of the objects instead of the hardcoded 1003-buffername.

**Comment by jdreske** [comment]
Thank you for the quick help. 
Adding some [change] objects did the trick. 
These hardcoded buffer-numbers appeared because I did not escape $0 with a backslash in the text editor I used to find and replace the buffer names in all objects.
Now I have to learn how to set up preset values correctly.
RTFM 🙄

**Comment by pierreguillot** [comment]
😉
