### ISSUE TITLE
Unable to get information about track or playhead from DAW

### ISSUE THREAD

**Issue by d-vyd** [pierreguillot/Camomile#48]
Hi Pierre,

Thank you so much for this project. I'm looking forward to integrating PD more closely with my DAW (MuLab). I'm having difficulty getting information about the track and playhead. One question is that the instructions (https://github.com/pierreguillot/Camomile/wiki/How-to-create-patches-for-the-plugin) refer to _$0-receive_ while the graphic example uses _$0-playhead_. I've tried both with no success. Here is one version of the simple PD patch I'm trying: [camomile_test1.zip](https://github.com/pierreguillot/Camomile/files/908311/camomile_test1.zip). I expect it to mimic the "tempo" setting inside the DAW. But, it does nothing. This issue has been confirmed by one other user in both MuLab and other DAWs: https://www.kvraudio.com/forum/viewtopic.php?f=79&t=482492&sid=2167123175a884d450d0b10cbe62399a

Could you provide an example patch to receive the track and playhead information? I'm trying to get a simple (but flexible) sequencer working. Thank you!

-d. vyd

**Comment by pierreguillot** [comment]
Hi,
I think the problem is that you want to display the bpm inside a number box. You can change the value of a GUI-object (number box, slider, etc.) from the DAW GUI but if its value has been changed from the pd patch, the graphical interface of the plugin is not updated in the DAW. I think that's why you think that you don't receive any information. I don't have time to install MuLab and test it right now but you can try the patch camo.cornetto that uses the playhead information also if you want to debug your patch you should use the [print] object. If you load this [patch](https://github.com/pierreguillot/Camomile/files/912912/playhead_test.pd.zip), normally you should be able to see the playhead information in the console (click on the "camomile flower" and then on "console"). You can have a look at the FAQ and perhaps also the other issues (the closed ones), I remember that other people had a similar issue. 

[playhead_test.pd.zip](https://github.com/pierreguillot/Camomile/files/912912/playhead_test.pd.zip)

**Comment by d-vyd** [comment]
Thanks for your advice. I'll give it a try later today!
________________________________

**Comment by pierreguillot** [comment]
Is your problem solved ?

**Comment by d-vyd** [comment]
Hi Pierre,


The patch you sent does indeed print correct information to the console. I haven't tried getting one of my patches to use your approach. I will so. Thanks for checking in.


-d. vyd

________________________________
