### ISSUE TITLE
Automatic reload of changed patches

### ISSUE THREAD

**Issue by elsueno** [pierreguillot/Camomile#52]
It would be really nice if changed / saved patches could be automatically reloaded.
Cross-platform file watching does not seem to be available in JUCE (correct me if I'm wrong here) but https://pocoproject.org/docs/Poco.DirectoryWatcher.html seems to make this easy but I'm not a C++ coder so I can't really tell wether that would work.

After a patch or subpatch has changed
* the state should be saved (needs thinking about what the state actually is and how to save it)
* audio should be faded out (like 1ms) to prevent clicking
* the new patch should be loaded
* the previously saved state should be restored
* audio should be faded in

That's probably not too easy to implement but would make patching so much more fun!

Thanks!

**Comment by pierreguillot** [comment]
I need to think about it, sometimes automatic reload can be annoying. Usually I save my patch every 10 seconds in case Pd crashes but I don't want my plugin to reload the plugin. Anyway the fade in/fade out is a good option because reloading a patch can be really painful for the ears :) Or perhaps we can add an option that enable the automatic reload...

**Comment by elsueno** [comment]
Yes sureI also think this should be optionally checkable in the plugin menu.

**Comment by pierreguillot** [comment]
I will keep the idea for a future release, not the next one because it's just an enhancement and I'm not sure that really compatible with my new changes.

**Comment by pierreguillot** [comment]
Moved to #59
