### ISSUE TITLE
Unable to send out MIDI events

### ISSUE THREAD

**Issue by stefankovatchev** [pierreguillot/Camomile#54]
I'm trying to send some random midi notes out to a plugin in reaper. Using loop midi as a midi output from PurrData and into Reaper works, but i can't get the notes to be recognized using camomile. I just started using this today, so i tend to think it's something I'm doing wrong. Any thoughts?

Camomile 0.0.7
Reaper 5.4
Windows 10
Pd-L2Ork (Purr-Data)

![2017-06-22 15_09_26-midirand pd - e__sk lib_user](https://user-images.githubusercontent.com/21224084/27458256-f88520c4-575c-11e7-87a3-64b8d02e8fff.png)

![2017-06-22 15_11_11-fx_ track 4](https://user-images.githubusercontent.com/21224084/27458274-0bc244aa-575d-11e7-9224-fee60e003d3c.png)

**Comment by pierreguillot** [comment]
Hi, it's better if you attach your patch because the properties of the GUI objects are important and they are not visible with in your screenshot. Nevertheless, for what I see I think you should use a [change] object between the toggle and the metro. See the issue #29 and #53 and and the [tutorials](https://github.com/pierreguillot/Camomile/wiki/How-to-create-patches-for-the-plugin)/[FAQ](https://github.com/pierreguillot/Camomile/wiki/Frequently-Asked-Questions).

**Comment by stefankovatchev** [comment]
Thank you Pierre, issue #22, #29, and #53 helped with my problem. With the addition on the change object and proper receives on my objects, everything is working fine. 

I'm also not able to see bangs and number boxes like Paulinho from issue #53, but i think the only supported objects in the gui are (toggle, slider, radio, comment, numbox) like you say on the pdpatchrepo.

Thanks for your work, this is great. All the best.
