### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/Camomile#60]
- [x] Bang
- [ ] Number 1 & 2
- [ ] Symbol 
- [x] Comment
- [x] Slider
- [x] Radio
- [ ] Array

**Comment by b2renger** [comment]
@pierreguillot well done and the work for the v1 release it's awesome. I definitely plan to use it when I have some time.

I was wondering if the choice of not supporting symbols could be reviewed ? I see one use case in particular were it could be handy : supporting osc communication - since libpd does include oscparse and oscsend.

a symbol could be used to let the user enter an ip / port number and even a parsing info eg "/accelerometer/x" to use it as an input into a plugin parameter, and let you map. This may be done with stuff like a osc2midi third party software.

Is there another way to let the user input text in a generated camomille plugin ?

**Comment by pierreguillot** [comment]
Thanks ! The symbol is supported in the last version. I didn't test it a lot but it seems to work. I implemented the atom number also. In fact the only missing GUIs are the VU-meter and the array (see #59 for my todo list).

**Comment by b2renger** [comment]
oh I see :) great ! I'll try to test this soon.
