### ISSUE TITLE
Feature Request : simplicity 

### ISSUE THREAD

**Issue by korakios** [pierreguillot/Camomile#72]
Hi,
Noticed that the new version is a bit confusing on loading a PureData patch (compared to 0.7)
Could someone make a tutorial on loading a patch ?
Loved the way on previous version , simply open a patch and run it .
Thank you for your time and hard work :)

**Comment by pierreguillot** [comment]
Hi,
> Loved the way on previous version , simply open a patch and run it .

I change the behavior because dynamic loading of patches is not well supported by the DAWs (for example, you can't have specific presets for a patch and sometimes the parameters are not even recognized). And the functionality implies other bugs (for example, the patch location depends on the machine, so if you share your project with another user, he has to reload all the patches in each plugin instance). In fact the principle of dynamic parameters is totally against the VST specification where most of the plugin's information should not change after its loading. You can also have a look at this issue #61 . 

I know it's more complicated but I didn't find a better approach of doing this. I guess, in fact the best solution would be to have a small program/interface that generates automatically the plugin with the patch for you but for the moment I don't have time to do it. But if some kind soul feels the necessity and the strength I'll be pleased to help him. Anyway, the generation of the plugin only take 6 actions that are very basic so I think the "difficulty" worth the benefit.

> Could someone make a tutorial on loading a patch ?

For the tutorial, did you look the [wiki](https://github.com/pierreguillot/Camomile/wiki)? And everybody can contribute so if you find a better way to explain you can change it. Or better if you can create a video, you can add the link (or ask me to do if you're really lost). 

Cheers

**Comment by korakios** [comment]
After some hours it was simpler than it looked like.

Windows64
Copy paste the pd patch to the vst folder, put the corresponding camomile (on windows there is vst3 or dll, no vst) file to the same vst folder , copy libpd to windows/system32 (for 64bit vst on 64bit host) and play!

Looking at 
https://github.com/pierreguillot/Camomile/wiki/v0.0.7---How-to-create-patches-for-the-plugin

I tried to make a simple patch ,but failed on Windows. Will try on linux first to see if it's my fault.

**Comment by korakios** [comment]
Ok, rephrasing :)

I am on Windows10 (will try later on Linux) . So the steps for making my own VST (nothing to do with the examples provided ) are : 

- Copy libpd to windows/system32
- Make a subfolder in my vst folder location called MyFirstVST
- Copy my simple midi channel change PureData patch called MyFirstVST to the above folde I made.
- Copy CamomileFX.dll ( since my pd patch is not an instrument ) , to the MyFirstVST folder and rename it to MyFirstVST.dll 
- Create the mysterious text file ! ( this is where the extra documentation is needed )

I look the text files of the examples , I get some hints about the options ,but have to admit I can’t make it work . Will wait patiently and a huge thank you for this project :)

**Comment by Lucarda** [comment]
Hi,

>Copy libpd to windows/system32

You are on Win10 64bit?

Does your **Daw** loads 64bit Vsts?

If not you should use the 32bit camomile and place the 32bit **libpd.dll** in the C:\Windows\SysWOW64 folder.

**Comment by korakios** [comment]
> You are on Win10 64bit?
Yes

> Does your Daw loads 64bit Vsts?
Yes!

> If not you should use the 32bit camomile and place the 32bit libpd.dll in the C:\Windows\SysWOW64 folder.

Fortunately the tip is on the wiki and the pdf guide, but thanks :)

**Comment by Lucarda** [comment]
So you see the plugin window on your host.

What is not working?
the MIDI thing?

**Comment by korakios** [comment]
> So you see the plugin window on your host.
What is not working?
the MIDI thing?

I do see the plugin, but I don't have a GUI . 
If I switch to basic view of the plugin in Reaper, I can see the name of the slider and the label correctly (meaning they match the names on the textfile), but my 'midi channel changer' doesn't work.
 I am sure I have something wrong in the textfile, will try some options but would love seeing a link where those options explained. 
 Plus more important I am sure that I haven't bridged correctly my patch with camomile , since I followed the guide from 0.7 older version. Will wait @pierreguillot or someone else for the new guide.

**Comment by Lucarda** [comment]
> Copy CamomileFX.dll ( since my pd patch is not an instrument ) , to the MyFirstVST folder and rename it to MyFirstVST.dll

You shold't use CamomileFX.dll, this has no MIDI in/out because is an audio fx. You should copy and rename the file "Camomile.dll" to your MyFirstVST.

**Comment by pierreguillot** [comment]
Hi,
@korakios @Lucarda @Alfonso73
I made this #73 if you want to start the create plugins before the tutorial is finished.

**Comment by pierreguillot** [comment]
Except if there are further questions or suggestions about the "simplicity" of the plugin, I will close this issue.

**Comment by korakios** [comment]
I don’t have any further , will try to make a video tutorial for a simple plugin when ‘connection to GUI’ comes to wiki page :)
In the meantime I’ll take a look at #73 ;)
