### ISSUE TITLE
Performance Differences between Pd and Camomile-plugin

### ISSUE THREAD

**Issue by jdreske** [pierreguillot/Camomile#84]
Is there any difference in audio performance between Pd and the Camomile-plugin? 
I noticed a patch I made produces crackling sounds in Ableton live until I increase the Blocksize to 256 or 512, while it sounds good in Pd with a Blocksize of 64 (both at 96kHz).
I double-checked I have inserted [change] objects after every gui object.

What could be the reason? Is there a difference between Pd and Ableton live?- 
or did I probably do something wrong in my patch?
It would be nice to get consistent output when working on the patch in pd and using it in live.

**Comment by pierreguillot** [comment]
Your GUIs objects only output when they are used, I don't think it makes a difference. You should probably use the `[change]` object when receiving the parameter's values:
```
[r param]
|
[route 1]
|
[change]
```
Or perhaps you created a loop somewhere between the patch and the plugin but you don't see it because the patch is not loaded in the plugin. In fact without the patch, I can't really tell. But if you don't have any problem with the example, I guess it's a patching problem.

**Comment by jdreske** [comment]
I just tried my plugin in logic - there are no problems so I guess it is a problem between Live and my Macbook. (The AlmondOrgan also produce clicks in Live when I set it to 96kHz and move some drawbar-sliders).

> Your GUIs objects only output when they are used

Ok, I think I got something wrong about that. 
I borrowed your abstraction to set the plugin parameters, it has a [change] object inside.

If you like to have a look at the patch, here is the au .component:
https://drive.google.com/open?id=10zXp8pqfKTRJeQrdyFh38e2Z8CV2nE2j
Work in progress and not as cleaned up as your examples but fun to play with. I'd be happy about some feedback.
Thank you for your great work!

**Comment by pierreguillot** [comment]
I also have glitches and artifacts on Reaper with your patch so I reopen the issue. Sometimes you should use `[line~]` instead of `[line]` but it doesn't seem to be the only problem. I guess there is something else that depends on Camomile.

**Comment by pierreguillot** [comment]
I'm bit lost in your patch, are you writing and changing the content of an audio buffer while you are reading it somewhere else?

**Comment by jdreske** [comment]
>  Sometimes you should use [line~] instead of [line]

I usually do, but in this case [line] worked good somehow.

The patch uses a FFT Equalizer to shape the incoming audio or or a built in [Noise~]-Audiosource
The volume of the frequencies are controlled by midi keys.
Thus you can extract a very small frequency band (sort of a sine wave) out of the audio input (or white noise). If you increase the width ('Q') the frequency bands get wider.
The patch also allows to produce octaves above the key pressed and one below, like a drawbar Organ.
To get fast results this organ features a built in chord :-)

If you  a look at the array 4 in pd (inside [pd arrays] on top of the main window) you can see what's going on. 
All the arrays just hold the volume information for the frequency bins. Since there is a lot of reading and writing this data I had to put a short delay (0.01 ms) between every read or write operation (hardcoded inside j_until.pd).

**Comment by pierreguillot** [comment]
As your patch is pretty complex, there are too many things that could generates the glitches. What's strange is that the sound becomes really distorted in Camomile only above 44100Hz... So I'll try to test separately several possible problems, starting with the FFT that is not really optimized for multi-instance and multithreading in PD. 

Anyway, even in Pd at 44100Hz I still ear small glitches when moving the slider (MacOS 10.13 - Pd0.48.1 & Tk8.6.6). But not the same bad glitches as with Camomile at 96000Hz. Also, it's more complicated but if you want to interpolate the values of an array, you should use two array and interpolate after reading the values of each array (in the time domain) as suggested by the Pd documentation. 

The investigation continues ;)

**Comment by jdreske** [comment]
> you should use two array and interpolate after reading the values of each array (in the time domain)

I will try this!

I have a lot of other work to do right now, but as soon as possible I will try to make a minimum patch from scratch that shows the problem. Something like this :
[http://www.pd-tutorial.com/english/ch03s08.html#id432343](http://www.pd-tutorial.com/english/ch03s08.html#id432343)
with adaptation to changing samplerates

best regards

**Comment by jdreske** [comment]
Here is a minimal FFT-Patch, which shows the problem.
FFT Blocksize and Overlapping is adjustable up to high values from the plugin
In Pd I hear no problems, but in Ableton there are glitches even at 44.1kHz.
-But If overlapping is off (set to 1) there are no glitches even at 96kHz (and Blocksize 32k)

[https://drive.google.com/open?id=1Yo6u6o1Q9VbOEyWL6BE7LYvO8ZfKqJ4o](https://drive.google.com/open?id=1Yo6u6o1Q9VbOEyWL6BE7LYvO8ZfKqJ4o)

(I don't know how the normalization works, so I just recalculate the normalization factor at 1.5*blocksize like in the tutorial patch. I did not try any up & downsampling either)

I hope this patch helps with troubleshooting.
best regards

**Comment by jdreske** [comment]
I made it even simpler, just a single FFT- same behaviour:
[https://drive.google.com/open?id=1Yo6u6o1Q9VbOEyWL6BE7LYvO8ZfKqJ4o](https://drive.google.com/open?id=1Yo6u6o1Q9VbOEyWL6BE7LYvO8ZfKqJ4o)

**Comment by pierreguillot** [comment]
I tried your last example and there are glitches also in Reaper. I made a [patch](https://github.com/pierreguillot/Camomile/files/1702834/ffttest2.zip) even simpler with just `[osc~ 220]` for the source and `[rfft~]` that goes directly to `[rifft~]` and there are also glitches at 96000Hz. So I guess the Pd's FFT is not well supported by the plugin. I'll try to figure out what can be the problem...

**Comment by pierreguillot** [comment]
I also try an even simpler patch without fft objects at all and there is no glitch so I guess it's the fft that causes the problem!

**Comment by pierreguillot** [comment]
After several tests, it seems that the version of the distribution has been compiled with **Debug** instead of **Release**. And the FFT of the **Debug** version is really slow. As I'm developing I use the **Debug** version and that's why the I also have glitches. I tried with a **Release** version and everything seems fine. I don't understand why the version of the distribution has been compiled with **Debug** as the script compile with the **Release** flag. Anyway I just ran another compilation, it must be with **Release** and here are the [binaries](https://github.com/pierreguillot/Camomile/files/1703430/CamomileMacOS.zip). I tried it and it worked, can you try with it also? 

Moreover, I investigated the Pd code and I found that the FFT doesn't support the multithreading so you can encounter problems with multi-instances. I will fix this and publish the v1.0.2 pretty soon after.

**Comment by pierreguillot** [comment]
I just try on Ableton 9.7.5 64-bit at 96000Hz - 64 samples, with 32 overlapping I don't have glitches until a block size of 8192 samples but on Reaper I never have glitches so I guess it's an Ableton limitation... Is it the same for you? Can you try with Reaper (it's free)?

**Comment by jdreske** [comment]
I just tried my first big patch in Reaper 96kHz, Blocksize 64 - works very well - no dropouts  at all !

So it seems to be a problem with Ableton live again...
By the way the dropouts are equally bad with the vst version of the plugin.
(I guess if I ask the Ableton support they will suggest to port the patch to Max4Live...)

I just tried the Bitwig Demo - It shows the same problems as live. 
Grrr.

**Comment by pierreguillot** [comment]
After more researches, it seems that crackles and audio dropouts are recurrent problems of Ableton Live. See [this](https://www.ableton.com/answers/ableton-9-0-6-pops-clicks-and-dropouts-at-40-cpu-help) for example but you can find easily other complains on the forums. I tried several solutions to optimize the FFT (with a better memory management, using single precision instead of double, etc.) but nothing improved the audio result and the CPU is still < 40%. As it works fine in Pd, Reaper and surely other DAWs, I guess that's the problem doesn't come from Pd nor the plugin but from Ableton or Bitwig. Perhaps certain DAWs have CPU restriction for the plugins... I don't know... I'll leave this for now because I'm out of ideas

**Comment by jdreske** [comment]
> Perhaps certain DAWs have CPU restriction for the plugins... I don't know...

That's also my suspicion. 

>  I'll leave this for now

👍 I'll  increase the blocksize or use another DAW.
