### ISSUE TITLE
1.0.2 Linux plugins not being detected by VST host

### ISSUE THREAD

**Issue by SeanArchibald** [pierreguillot/Camomile#89]
I have generated plugins for the 4 example projects (AlmondOrgan, Bulgroz, Castafiore, MiniMock) by following the instructions on this page: https://github.com/pierreguillot/Camomile/wiki/How-to-generate-plugins

My OS is Ubuntu MATE 17.10. Camomile version is 1.0.2 (CamomileLinux64.zip downloaded from https://github.com/pierreguillot/Camomile/releases)

I added the corresponding Camomile plugin file (Camomile.so or CamomileFx.so) to each example project directory, and then copied each project directory to ~/.vst/

None of these 4 plugins are being detected in the 2 DAWs I've tested: Bitwig and Reaper.

I have tried setting perms of the plugin files to 777. Tried moving the files to other locations outside of my home directory.

Many thanks! I’m so glad this project exists and I'm excited to get started

**Comment by SeanArchibald** [comment]
Below is the error log output from Bitwig:

```
/home/s/.vst/Camomile/AlmondOrgan/AlmondOrgan.so

com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Could not read VST plug-in metadata
64 bit plugin host reported errors: Pluginhost returned non zero exit code 255

32 bit plugin host reported errors: Pluginhost returned non zero exit code 255
```

I googled for the above Bitwig error message but it seems to be a generic message.

Reaper doesn’t show any error output, however the plugins I generated don’t appear in my plugins list after a rescan.

**Comment by pierreguillot** [comment]
Yes, because I'm a idiot and I forgot to add the libpd library in the Linux distribution... thanks a lot for reporting this! So for the moment, you can wait for the next release or if you want to use Camomile right, you can compile libpd from the master branch of Camomile. For this, follow these instructions [How to compile the plugins](https://github.com/pierreguillot/Camomile/wiki/How-to-compile-the-plugins)  and stop after `make -C libpd/ UTIL=true EXTRA=true ADDITIONAL_CFLAGS="-DPDINSTANCE=1 -DPDTHREADS=1"
` (or now you can do `make -C libpd MULTI=true` that does exactly the same), you don't need to compile the plugins. Then, you'll find the library **libpd.so** in the folder **libpd/libs** and you'll only have to install the library on your system.

**Comment by pierreguillot** [comment]
beta1
[CamomileLinux64.zip](https://github.com/pierreguillot/Camomile/files/1736800/CamomileLinux64.zip)

**Comment by SeanArchibald** [comment]
Tested with MiniMock, AlmondOrgan and Bulgroz - all working as normal with Bitwig on Ubuntu 17.10! 🎉

**Comment by pierreguillot** [comment]
v1.0.3 is now available on the release page
