### ISSUE TITLE
Saving/recalling content of text object

### ISSUE THREAD

**Issue by SeanArchibald** [pierreguillot/Camomile#91]
Is there a way to store the data inside a text object so that it can be recalled when the user reloads a project?

Here is my use case: My synth uses a text object to store 128 frequency values (floats) - that's one frequency for each MIDI note. Instead of using the mtof object, I get frequencies from this text object. This works totally fine, but when I save and reload my project, the data inside the text object is lost. Is there a way to save this data - or should I use some other method to save the 128 values?

I have attached a zip which contains a very basic Camomile project to demonstrate the problem. It also contains the Mac .vst and 2 tuning files (exampleTuning.txt and 5edo.txt) for testing.

[camomile_cosine_synth.zip](https://github.com/pierreguillot/Camomile/files/1732292/camomile_cosine_synth.zip)

I have to say this just one more time... thank you Pierre for this amazing project!

**Comment by pierreguillot** [comment]
I guess the best solution for the moment is to dynamically write the content of the text object in the plugin bundle/folder and to reload it at startup. I know, there are still problems with this approach: 
- You can write the file only after its loading but it would be better to write the file when saving the project or when saving the plugin state (because sometimes you load a file just for testing you don't want it to be saved with the project).
- You can have only one file so you if you have several instances, one instance will overwrite the files of the others.

**Comment by pierreguillot** [comment]
In fact, I planned to implement a save and load mechanism. When the DAW save the plugin state, the plugin can notify the patch (with for example a bang via the symbol `save`). And then the patch can send back the data to save to the plugin (with a message `save` followed by arguments via the symbol `camomile`) . And when the DAW reloads a plugin state, the plugin can send back the data to the patch (via the symbol `load`). This could be also useful for programs (presets). 

The question that remains is how to specify the data to save because it could be a list of atoms (float and symbols) but for some cases I guess it would not be sufficient. Perhaps using key words like:
- `list` if you just want to save a list
- `array` if you just want to save the content of an array object
- `text` if you just want to save the content of a text object

Perhaps, you could also send several `save` messages and at loading the patch will receive several messages via the `load` symbol. 

If you have any technical specification, feel free to ask!
Cheers

**Comment by 18musicians** [comment]
Hey @SeanArchibald  -  I was thinking about the same things, and for the same reason.  It might be more of a Pd question, rather than a Camomile question.  I would guess that loading scala files would be possible but a little beyond my amateur Pd skills at this point.  A couple of days ago I found this, which looks like it could be helpful:    
https://forum.pdpatchrepo.info/topic/7607/temperament-a-mtof-for-more-or-less-historical-tunings 
It's not a format that you or I would want to use for a tuning table, but may give some good ideas on how to implement your preferred format.  I've only taken a really quick scan of the txt file format and haven't had time to dig deeper yet into what the patch is doing.  Looks like the user can choose from a list of pre-selected tunings already compiled into one specific text file.  What I still haven't found is a way for a user to select a file.  If someone opens a Camomile patch from a DAW and wants to load up a tuning file (or any other kind of arbitrary settings file), how would they be able to navigate to and select a file?  (Again, I don't know if this is a Camomile question or a Pd question...)

**Comment by SeanArchibald** [comment]
I will be using several instances of the plugin with different .txt files loaded, so using just 1 txt file is not an option here.

I'm more familiar with traditional programming and Max/MSP, so I'm still uncertain how I will find a solution using Pd/Camomile. I just really want to store 128 values in an array, let the array be saved/recalled on a per-instance basis, and get a value from the array every time a midi note is received.

Possible solutions I'm thinking of:
- Store the path to the txt file - is this possible?
- Store my 128 values in a list or array - can Camomile save/recall this data when I reload the plugin instance?
- Store 128 values individually, each as a single param. Very time consuming to set up, I can't seem to find an efficient way to set up my plugin like this.

**Comment by SeanArchibald** [comment]
@18musicians the attachment on my original post is a Pd/Camomile project that has the working scale import (via txt file) and oscillators playing at the correct frequency. For your question about how users can select a file to load from their computer, go to issue #73 and check 'How to use openpanel and savepanel'

The Camomile-specific question here is: when I save the project in my DAW, how can Camomile store the contents of the text object so that it is recalled when I re-open the project later?

This is the last "big" problem I have to solve with Camomile, but when a solution is found I'll share any of my microtonal instruments with you @18musicians! :)

**Comment by Lucarda** [comment]
On 2/17/2018 2:39 PM, Sean Archibald wrote:
> The Camomile-specific question here is: when I save the project in my 
> DAW, how can Camomile store the contents of the text object so that it 
> is recalled when I re-open the project later?


You can use only 1 txt file and this one has all your tunings but 
separated with an onset.


from line 1 0 to 128 tuning 1

 From 150 to 278 tuning 2

 From 300 ....


Since all your tunings are in a single file you always load that file 
but you can use a preset to store/recall the onset.

Your preset can have have another mapping:

1 = 0

2 = 150

3 = 300

..

Mensaje telepatico asistido por maquinas.

**Comment by SeanArchibald** [comment]
@Lucarda I haven't explained my use case very well, so it's not obvious to others why I can't store all my tunings inside a single file. I do really appreciate your input, and if you would prefer to know why I won't store all tunings in a single file, we can talk outside this thread about my project requirements.

@pierreguillot so it sounds very troublesome for you to get this working. In that case feel free to close the issue... But my follow up question will be: is it possible to save/recall a symbol that contains a file path? :)

**Comment by Lucarda** [comment]
On 2/17/2018 3:23 PM, Sean Archibald wrote:
> is it possible to save/recall a symbol that contains a file path? :)

Why can't you do that with another [textfile]?



Mensaje telepatico asistido por maquinas.

**Comment by SeanArchibald** [comment]
Each **instance** of my plugin must be able to remember its own 128 frequencies. If I understand correctly, Camomile won't allow for each instance to have its own set of frequencies - each instance must share the same set. Any solutions are appreciated.

**Comment by Lucarda** [comment]
On 2/17/2018 3:57 PM, Sean Archibald wrote:

Each instance of my plugin must be able to remember its own 128 frequencies. If I understand correctly, Camomile won't allow for each instance to have its own set of frequencies

Why do you think it will not?
You know the "$0-" thing (2.control.examples/13.locality.pd)



- each instance must share the same set. Any solutions are appreciated.

I think you didn't mean "each instance must share the same set".

Every instance will have parameters saved in the DAW.
You can use this "Parameter" to load what you need in each instance.
For simplicity use parameter 1,2,3,4,....
You can use this simple value as a "line" for [text get John].
You can have in [text define john] 1 file/path per line. (here you specify each tuning file per line)
So your [loadbang] has to trigger your parameter, that will load a "unique tuning per instance".
This way when you reopen your DAW you have all instances with it's tunings.

Is this what you need?







Mensaje telepatico asistido por maquinas.

**Comment by Lucarda** [comment]
@SeanArchibald 

May be this pic is a better example of what i think you are asking:
![ex1](https://user-images.githubusercontent.com/25239522/36345254-ed9c442e-1405-11e8-82d1-2e9ce364bd2f.jpg)

**Comment by SeanArchibald** [comment]
@Lucarda your solution looks like it would work, but do you think it's robust? If I send my DAW session files to my collaborator, and he has been using his local copy of my plugin, then his z.txt will differ from my z.txt, and so he will load my project with the incorrect data. This solution isn't robust for multi-user, multi-instance, multi-project situations. It would be extremely simple if the tuning data could be directly saved with the DAW session data, like other VSTs are able to do. I'm so thankful for your ideas though and I hope you're able to understand my concerns.

Pierre sorry we gave you a lot to read 😁  hope you will still see my previous questions from earlier today ^

**Comment by pierreguillot** [comment]
Hi,
The approach by @Lucarda is good only if the possible states of the array are aleady known by the plugin. In this case, depending on the value of a parameter, the plugin can use the 1st/2nd/3rd/etc table. The problem raised by @SeanArchibald is when the plugin don't know all the possible states of the array. In this case, you can't use a parameter. 

Prehaps a more simple case would be that you have a graphical inteface to draw the content of an array. The number of possibilities for the content of the array is almost infinite and you can't a have some kind of meta value that represent the content. To save the content of the array, the only solution for the moment would be create a parameter for each sample of the array. But imagine for example that the array has 2048 samples (that is not really big) the plugin already needs 2048 parameters... that not usable. And what if the size of the array could change dynamically?

So if I generalize the question, it would be: How to save and reload data that cannot be represented by parameters ? Here is the solution #73 ;) It will be available with v1.0.3!

**Comment by SeanArchibald** [comment]
That's fantastic. Big thanks to everybody on the thread.

@pierreguillot Can I ask if v1.0.3 will also allow you to save the state of a text object? If not, I'm sure I can still get everything working fine by using an array instead - just curious!

**Comment by pierreguillot** [comment]
Something like that should work
<img width="332" alt="screen shot 2018-02-19 at 4 33 30 pm" src="https://user-images.githubusercontent.com/1409918/36385395-c0682818-1592-11e8-819c-66ca907e6918.png">
